server:
  port: 8080
  #servlet 上下文路径
  servlet:
    context-path: /cqchat_sys

spring:
  datasource:
    name: cqchar_sys
    #采用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    #连接数据库的url
    url: jdbc:mysql:///cqchat
    #用户名 密码
    username: root
    password: 123456
    #驱动类
    driver-class-name: com.mysql.cj.jdbc.Driver
    #监控统计
    filters: stat
    initial-size: 2 #初始化连接
    max-idle: 10 #最大空闲连接数
    min-idle: 1 #最小空闲连接数
    max-wait: 60000 #获取连接超时的等待时间
    max-active: 20 #最大活动连接
    time-between-evict-runs-millis: 60000 #检测关闭空闲连接
    min-evictable-idle-time-millis: 3000000
    validation-query: SELECT 'X'
    test-while-idle: true
    test-on-borrow: false


